### ISSUE TITLE
Re-compile

### ISSUE THREAD

**Issue by NukeExplosions** [csnxs/Terraria#5]
Sorry, bit of a newbie but how do you recompile this?

**Comment by Sylk** [comment]
Please do not.

**Comment by lawlon** [comment]
One of the funniest replies i've seen on github.

@NukeExplosions to give you a TL;DR.
Don't, you'll most likely get sued if you try.

**Comment by NukeExplosions** [comment]
Lol, i was a complete idiot when i asked this. I was trying to mod the game... Anyway, i did mod it with tmodloader in the end.
