### ISSUE TITLE
there are some weird characters

### ISSUE THREAD

**Issue by LinkerJL** [csnxs/Terraria#6]
For example, in `Main.cs`
```
    public Main()
    {
      base.\u002Ector();
      Main.instance = this;
      Main.graphics = new GraphicsDeviceManager((Game) this);
      this.get_Content().set_RootDirectory("Content");
    }
```
How to fixed it?

**Comment by luciusmagn** [comment]
Looks like improper decompilation. \u002 is a unicode escape sequence. What
I can tell you is that this line calls parent class's constructor, so you
can just remove the like and do

public Main() : base()
{
//... rest of the stuff
}

2017-11-02 9:47 GMT+01:00 LinkerJL <notifications@github.com>:

**Comment by LinkerJL** [comment]
Thanks, @luciusmagn .
I decompiled the latest version of Terraria.exe with dotPeek yesterday, and found no `\u002Ector` any more.

However, I found other problems. Some have been figured out, some haven't.

1. sample code
```c#
// ISSUE: explicit reference operation
// ISSUE: variable of a reference type
int& local3 = @Main.tileFrameCounter[390];
// ISSUE: explicit reference operation
int num5 = ^local3 + 1;
int num6 = num5;
// ISSUE: explicit reference operation
^local3 = num6;
if (num5 >= 8)
```
According to [Unusual C# operators in decompiled source…?](https://stackoverflow.com/questions/13923226/unusual-c-sharp-operators-in-decompiled-source)
Seems that dotPeek can't deal with +=, -=, *=, /= properly. The code above should be
```c#
Main.tileFrameCounter[390] += 1;
if ( Main.tileFrameCounter[390] >= 8)
```

2. sample code
```c#
private static void TrySupporting8K()
{
  if (!Platform.get_IsWindows())
    return;
```
`IsWindows` is property. The code above should be
```c#
private static void TrySupporting8K()
{
  if (!Platform.IsWindows)
    return;
```

3. sample code
```c#
// ISSUE: variable of a boxed type
__Boxed<int> local = (ValueType) num;
```
Still have no idea yet.


I hope this helps others with the same problems.
