### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by CodeProgrammer0** [csnxs/Terraria#7]
Hello will you please remove this, as it violates the ToS or I am willing to report you thanks.

**Comment by andrewgosselin** [comment]
lol alright CODEPROGRAMMER0, you joined 6 days ago. Don't try to get people to remove things that have nothing to do with you. This does not violate the terms of service, please read them and come back. If you actually took the time to read the readme then you would know "This repo does not include the game content. If you want the content, buy the game on Steam." its just decompiled code.

**Comment by stefnotch** [comment]
@andrewgosselin

I'm afraid that I cannot find the Terraria EULA at all. (Could you link me to it?) However, I found this semi-official response from a Terraria forums administrator:

> I'm assuming that you are talking about the PC Windows version here (and soon to be on OSX and Linux).

You cannot distribute any of Terraria's source code, and you may not distribute a modification which bypasses Steam's DRM. You also cannot distribute a modification that provides the game for free. A patch, DLL or binary diff would be preferable - something that could be applied to a valid copy of the game. Standalone EXE's are suspicious to us and may require prior approval of Re-Logic to distribute here.

If you're talking about mods for the Console or Mobile versions (any platform) - we do not permit mods for either on this site.
-- TunnelKing

https://forums.terraria.org/index.php?threads/eula.21697/

**Comment by Skii7niX** [comment]
https://terraria.org/terms
Only section that pertains to this is

> "Permission is granted to temporarily download one copy of the materials (information or software) on Terraria's web site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
> 
> modify or copy the materials;
> 
> use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
> 
> attempt to decompile or reverse engineer any software contained on Terraria's web site;
> 
> remove any copyright or other proprietary notations from the materials; or
> 
> transfer the materials to another person or "mirror" the materials on any other server."

**Comment by CodeProgrammer0** [comment]
A

**Comment by CodeProgrammer0** [comment]
After reading over the Tos and comments I have decided to report this as abuse.

**Comment by SOSFILMZ** [comment]
You didn't even explain anything, you just jumped in and said "I might report this bc I **think** it violates ToS" followed by "I'm reporting this as abuse!"
I seriously doubt your report is going to do anything.

**Comment by CodeProgrammer0** [comment]
Do not message me anymore. I did what I needed to do.
